app = "fly-mongo"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

# uncomment [[services]] section to make it available publicly
#[[services]]
#  internal_port = 27017
#  auto_stop_machines = false
#  min_machines_running = 1
#  protocol = "tcp"
#  [services.concurrency]
#    hard_limit = 25
#    soft_limit = 20
#    type = "connections"
#
#  [[services.ports]]
#    port = 27017
#
#  [[services.tcp_checks]]
#    grace_period = "1s"
#    interval = "15s"
#    restart_limit = 0
#    timeout = "2s"

[[mounts]]
  destination = "/data/db"
  source = "storage"
  initial_size = "1GB"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"    

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
